---
title: "hippocampal pyramidal cell somatic current injection experiment"
author: "Balazs B Ujfalussy"
date: "11/09/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Analysing spiking in hippocampal pyramidal neurons. Data provided by (Dr. Judit Makara)[ http://koki.hu/organization/neuronal-signaling]. Patch clamp recording from the somata of a CA3 pyramidal neuron during somatic current injections. The dataset includes three repetitions using the same stimulus.

Reading the data.
```{r}
data <- read.table('./Data/SingleNeuron_Makara_5000Hz.dat', header=T, sep=" ")
stim <- data[,1]
resp <- data[,-1]
t <- seq(1/5000, by=1/5000, length=nrow(data))
```

Plotting the response...

```{r}
layout(matrix(c(1,2), nrow=1), c(2,1))
par(mar=c(4,4,3,4))
matplot(t, resp, t="l", lty=1, ylim=c(-80, 40), axes=F, xlab="time (ms)", ylab="membrane potential (mV)"); axis(1); axis(2, las=2)
lines(t, stim/10-80, col=4)
axis(4, c(-80, -55), c(0, 250), col=4)
mtext('current (pA)', 4, 2, adj=0)
legend('topleft', c('repetition 1', 'repetition 2', 'repetition 3', 'stimulus'), lty=1, col=1:4, bg=grey(1, alpha=0.75))

par(mar=c(4,1,3,1))
n1 <- 1.3*5000
n2 <- 1.8*5000
matplot(t[n1:n2], resp[n1:n2,], t="l", lty=1, ylim=c(-80, 40), axes=F, xlab="time (ms)", ylab="membrane potential (mV)"); axis(1)
lines(t[n1:n2], stim[n1:n2]/10-80, col=4)
```



